### ISSUE TITLE
GameSettings: 'BrokenNodeDetector' is not found or cannot be loaded

### ISSUE THREAD

**Issue by originalfoo** [krzychu124/BrokenNodeDetector#1]
Getting this in log file (seems to occur at end of loading screen so it's near bottom of attached log file):

```
GameSettings: 'BrokenNodeDetector' is not found or cannot be loaded. Make sure to call GameSettings.AddSettingsFile() to register a settings file before using SavedValue().  [Settings - Internal]
```

[output_log.txt](https://github.com/krzychu124/BrokenNodeDetector/files/3355245/output_log.txt)

**Comment by krzychu124** [comment]
Internal implementation of `SettingsFile` loader always pushing this info to log. There is no way to skip that AFAIK
