### ISSUE TITLE
Find (or jump to next) stucked cims and vehicles

### ISSUE THREAD

**Issue by bliet** [krzychu124/BrokenNodeDetector#14]
### Describe your idea
Button: Find (or jump to next) stucked cims and vehicles

At the moment there is a button "Reset stuck cims and vehicles". Nice so far. 
But where this cims are stucked? With this info I could fix the issue that cause the problem.
At the moment I press this button every x minutes.. without fixing the cause.

**Comment by krzychu124** [comment]
I'm working on such feature for [BrokenNodeDetector](https://github.com/CitiesSkylinesMods/BrokenNodeDetector) (probably will rename that mod to _Broken Things Detector_ or similar😂 )
I can transfer this issue to that repository if you want so won't generate duplicates 😉

**Comment by kianzarrin** [comment]
Transfer manager can tell if a tram is stuck. not sure if that is relevant. It can also allow you to move from one to another stuck vehicle to delete them. but its a bit clunky.

**Comment by aTadnMad** [comment]
yes.  a feature to find nodes that node controller made too big!  cims will get stuck at this intersection, but with a vast city of 837,234 people, finding these nodes becomes a nightmare at best.  i imagine it's just a simple `if "node.width >= 65 || node.height >= 65"` statement.

**Comment by krzychu124** [comment]
hint: it may not be a road node. Breaking invisible pedestrian paths created for (over)underground metro/train can cause similar issues. The just stuck and wait. If you try _Node Controller Renewal_ Beta it should help (has a fix for node size) 
> i imagine it's just a simple if "node.width >= 65 || node.height >= 65" statement.

No it's not that simple...

**Comment by aTadnMad** [comment]
> hint: it may not be a road node. Breaking invisible pedestrian paths created for (over)underground metro/train can cause similar issues. The just stuck and wait. If you try _Node Controller Renewal_ Beta it should help (has a fix for node size)

ok, i've never seen it happen anywhere else.  just on nodes larger than a certain size (50m?) can't recall.  I'll try the beta, for sure!

> 
> > i imagine it's just a simple if "node.width >= 65 || node.height >= 65" statement.
> 
> No it's not that simple...

haha.  maybe not :D

**Comment by krzychu124** [comment]
_Stuck cim detector_ already Implemented and released to the workshop in **v.0.7.x+**
