### ISSUE TITLE
New text/image for worksop page?

### ISSUE THREAD

**Issue by originalfoo** [krzychu124/BrokenNodeDetector#7]
![image](https://user-images.githubusercontent.com/1386719/72827820-63b60400-3c73-11ea-9f24-740eb4dd8da7.png)

Locates invisible problems with your transport system and helps fix them.

Press **Ctrl+Zero** in-game to display the mod panel.

### Fix broken nodes

The [broken node bug](https://github.com/CitiesSkylinesMods/TMPE/issues/277) causes vehicles to despawn when they reach a certain segment of road or rail. 

* Click **Run detector** to scan the city
* It will find one problem at a time and highlight it on the map
* Either bulldoze it or move it slightly to repair
* Repeat the process until no problems found

### Fix ghost nodes

Ghost nodes can cause "Array Index" errors and problems with pathfinding.

* Click **Remove Ghost Nodes** to find and remove any ghost nodes

### Fix transport routes and stops

Broken transport routes can prevent vehicles from spawning or prevent cims from reaching their destinations.

* Click **Detect disconnected PT stops** to scan the city
* Problems are listed one at a time; click **Find next** to see each one
* Click **Remove** to delete a broken line or stop

### Links

* Source code
* Changelog
* Discord Chat

**Comment by krzychu124** [comment]
Yeah, looks nice :)

**Comment by krzychu124** [comment]
Damn.. I completely forgot about that 😄

**Comment by krzychu124** [comment]
Done :)
